version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    env_file: ./.env.example
    ports:
      - "18080:18080"
    networks: [space]

  client:
    image: node:20
    working_dir: /app
    volumes:
      - ./packages/client:/app
    command: sh -c "corepack enable && pnpm i && pnpm build && pnpm preview --host 0.0.0.0 --port 5173"
    ports:
      - "15173:15173"
    depends_on: [server]
    networks: [space]

networks:
  space:
    driver: bridge
