services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    env_file: ./.env.example
    ports:
      - "18080:8080"
    networks: [space]

  client:
    image: node:20
    working_dir: /app
    volumes:
      - ./packages/client:/app/packages/client
      - ./packages/shared:/app/packages/shared
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
    command: >
      sh -lc "corepack enable &&
              pnpm install &&
              pnpm --filter @game/client build &&
              pnpm --filter @game/client preview --host 0.0.0.0 --port 5173"
    ports:
      - "15173:5173"
    depends_on: [server]
    networks: [space]


networks:
  space:
    driver: bridge
